services:
  postgres:
    image: postgres:17
    container_name: monolit 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: monolit 
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    restart: unless-stopped

volumes:
  postgres_data:
